spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    console.path: /h2-console
  redis:
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  secret: asd;ofinas;ldfnasl;dfnasdkjnfaklsdbvjbjawhbewjksldnbckajncvkdjvbna
